### PR TITLE
Change from ValheimLib -> JotunnValheimLib

### PR DESCRIPTION
**Pull request by sbtoonz**

### CODE REVIEW

**Comment by sbtoonz** [comment]
Valheimlib has become defunct and no longer supported 

this alters your mod to use JVL instead 
@rolopogo

**Review by werner-mayer — APPROVED** [review]
paciently waiting for the new version in thunderstore

**Comment by DartagnanFreire** [comment]
Waiting for this

**Comment by sbtoonz** [comment]
Well since this mod is MIT licensed with no reply from author I will upload the refactored copy

**Pull request closed without merging**
